// source/vue/button/button-component.vue
<style lang='css'>
  @import '../../../node_modules/@togakure/styles/lib/css/06-components/button.css';
</style>

<script>
import { styles } from '@togakure/styles';
const classes = styles.button;
export default {
  name: 'tog-button',
  data: () => {
    return {
      classes
    };
  },
  props: {
    type: {
      type: String,
      default: 'default'
    },
    size: {
      type: String,
      default: 'medium'
    },
    outline: {
      type: Boolean,
      default: false
    },
    active: {
      type: Boolean,
      default: false
    },
    block: {
      type: Boolean,
      default: false
    },
    rounded: {
      type: Boolean,
      default: false
    },
    circle: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },
    loading: {
      type: Boolean,
      default: false
    }
  },
  computed: {
  }
};
</script>

<template>
  <button :class="[
    classes[type],
    classes[size],
    { [classes.outline]: outline },
    { [classes.active]: active },
    { [classes.rounded]: rounded },
    { [classes.circle]: circle },
    { [classes.block]: block },
    { [classes.loading]: loading }
  ]"
  :disabled="disabled"
  ><slot></slot></button>
</template>

// source/angular/button/button-component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { styles } from '@togakure/styles';

@Component({
  selector: 'tog-button',
  template: `
    <button
      (click)="onClick.emit($event)"
      type="{{type || 'button'}}"
      [ngClass]="classes"
    >
    {{ text }}
    </button>
  `,
  styleUrls: ['../../../node_modules/@togakure/styles/lib/css/06-components/button.css']
})

export default class ButtonComponent {
  @Input()
  className: string;
  
  @Input()
  style: string;
  
  @Input()
  type: string;
  
  @Input()
  text: string;
  
  @Input()
  size: string;
  
  @Output()
  onClick = new EventEmitter<Event>();

  public get classes(): string[] {
    const mode = styles.button[this.style];

    return [styles.button[this.size], mode];
  }
};
