// source/angular/tag/tag-component.ts
import { Component } from '@angular/core';
import { styles } from '@togakure/styles';

@Component({
  selector: 'tog-tag',
  template: '<div></div>',
  styleUrls: ['../../../node_modules/@togakure/styles/lib/css/06-components/tag.css']
})

export default class TagComponent {
  public get classes(): string[] {
    return [styles.tag];
  }
};

// source/vue/tag/tag-component.vue
<style lang='css'>
  @import '../../../node_modules/@togakure/styles/lib/css/06-components/tag.css';
</style>

<script>
import { styles } from '@togakure/styles';
const classes = styles.tag;
export default {
  name: 'tog-tag',
  data: () => {
    return {
      classes
    };
  },
  props: {
    type: {
      type: String,
      default: 'default'
    }
  },
  computed: {
  }
};
</script>

<template>
  <div :class="[
    classes[type]
  ]"><slot></slot></div>
</template>
